version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    working_directory: ~/hello
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore 
     # - run:
     #      name: Test
     #      command: |
     #        dotnet test 
      - run:
          name: Build
          command: |
            dotnet build 
  deploy:
      docker:
        - image: appmanagm/hello.api.core:latest
      working_directory: ~/hello        
        - checkout
        - run:
            name: pack
            command: dotnet pack hello.api.core --configuration=DEV --include-symbols --output nupkgs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master 