version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.300-preview2-sdk-alpine
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
    # - run: dotnet test --no-build Build.Tests
  deploy:
      docker:
        - image: appmanagm/hello.api.core:latest
      working_directory: ~/hello    
      steps:    
        - checkout
        - run:
            name: pack
            command: dotnet pack hello.api.core --configuration=Dev --include-symbols --output nupkgs
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master 